music_directory "~/Music/library/"
playlist_directory "$XDG_CONFIG_HOME/mpd/playlists"
log_file "$XDG_RUNTIME_DIR/mpd_log"
bind_to_address "$XDG_RUNTIME_DIR/mpd_socket"
user "olorochi"
restore_paused "yes"
auto_update "no"
follow_outside_symlinks "yes"
follow_inside_symlinks "yes"
replaygain "album"

input {
    plugin "curl"
}

audio_output {
    type "alsa"
    name "ALSA output"
}
