#! /bin/sh

pos=$(mpc -f '%position%' current)
song=$(mpc playlist \
	| fzf --tac --sync --raw --scroll-off 999999 \
		--bind "start:pos(-$pos)" \
		--bind "ctrl-h:pos(-$pos)" \
		--bind "ctrl-b:best" \
		--accept-nth '{n} + 1' \
	| bc \
	| sed "s/'/\\\'/g")

[ -n $song ] && mpc play $song
