#!/bin/sh

bat=/sys/class/power_supply/BAT1
while :; do
    song="$(mpc current) $(mpc status %percenttime%)"
    load=$(cat /proc/loadavg)
    power="$(cat $bat/capacity)% [$(cut -c 1 $bat/status)]"
    ram=($(free -Lh))
    date=$(date +'%Y-%m-%d %X')
    echo "$song | $load | ${ram[*]} | $power | $date"
    sleep 1
done
